# This uses a reusable workflow
name: Reusable Workflow to add a assignee to issues

on:
  issues:
    types: [opened]

jobs:
  do-it:
    uses: ./.github/workflows/add_assignee_to_issue_reusable.yml
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        USER: ${{ secrets.USER }}