name: Publish mkdocs with mike version reusable

on:
  workflow_call:
    inputs:
      doc_version:
        description: 'The version of the documentation to be publish.'
        required: true
        type: string

jobs:
  publish_mkdocs_with_mike_version:
    runs-on: Ubuntu-20.04
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git user
        uses: fregante/setup-git-user@v2

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Publish Mkdcos with Mike
        run: mike deploy --push --update-aliases ${{ inputs.doc_version }} latest
