# This uses a reusable workflow
name: Reusable Workflow to set due date to closed issue

on:
  issues:
    types: [closed]

jobs:
  do-it:
    uses: ./.github/workflows/set_due_date_to_orgs_closed_issue_reusable.yml
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ACCOUNT: ${{ secrets.ACCOUNT }}
        PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
