# This uses a reusable workflow
name: Test

on: push

jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - name: See repo name
        env:
          NAME: ${{ github.event.repository.name }}
        run: echo $NAME
      - name: See repo owner/name
        id: split
        env:
          OWNER_NAME: ${{ github.repository }}
        run: echo "::set-output name=owner::${OWNER_NAME##*/}"
      - name: Test variable owner
        run: |
          echo ${{ steps.split.outputs.owner }}
